[General]
Background=background.jpg
Primary=#dabaf9
OnPrimary=#3e2459
Secondary=#d0c1da
Surface=#151218
SurfaceVariant=#4a454e
OnSurface=#e8e0e8
OnSurfaceVariant=#ccc4cf
Outline=#968e98
Error=#ffb4ab
FontFamily=JetBrainsMono Nerd Font
DefaultUser=justas
